### ISSUE TITLE
Show documentation preview does not work with DLang.

### ISSUE THREAD

**Issue by lavocatt** [vushu/coc-dlang#2]
Using this configuration:

```
" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>
```
I can't get to the documentation to show up in a popup. It's working on other languages on my configuration. Do you have an idea on what could be missing ?

System setup:
- Neovim v0.8.0
- Fedora 36

**Comment by vushu** [comment]
Hmm it's seems like there is problem with current serve-d, I need to investigate it.

**Comment by lavocatt** [comment]
Do you know if there's a way to turn on logs for serve-d using your extension ?

**Comment by vushu** [comment]
@lavocatt not currently, but I have answered your issue https://github.com/Pure-D/serve-d/issues/272

**Comment by lavocatt** [comment]
Thanks a lot!

**Comment by vushu** [comment]
does K work if you move the cursor not at the first letter of the word you want to read document from?

**Comment by lavocatt** [comment]
Yes! It works when I'm pressing K on the last letter of the word, do you have an idea why ?

**Comment by vushu** [comment]
@lavocatt yes it's a bug, which is fixed in this commit, https://github.com/Pure-D/serve-d/commit/b84efa140687c351ce15467f604d9e13d9ae9227, but we can't yet benefit from it before the latest version of serve-d works for coc.

**Comment by lavocatt** [comment]
So cool you found it! Let's wait until `serve-d` is fixed then!

**Comment by vushu** [comment]
closing this because of fix: https://github.com/Pure-D/serve-d/commit/2bd513a012901a47560e0f69163841aefc61a752
