### ISSUE TITLE
serve-d 0.8.0 beta 10 doesn't work on vim + coc

### ISSUE THREAD

**Issue by monkoose** [vushu/coc-dlang#3]
Seems like it is not completely related to this project. Because i tried it to get working without coc-dlang with the same issue - that coc is notifying with `connection to server is erroring` message. The same serve-d version is working fine on neovim + it's lsp.

Is it working for you? I have found some similar issue on `serve-d` issues tracker with your participation, but before updating that one or creating new one, wanted to ask here first if `coc-dlang` with latest serve-d beta is working for you.
Release version of `serve-d 0.7.4` isn't working for me either but with a different cause of the error (requests package old openssl or something).

**Comment by vushu** [comment]
@monkoose, sadly the latest beta version of `serve-d `haven't been working on coc for some time now, so I haven't had it working for me either. There has been some major changes to serve-d and I have also spend some time looking into it, but had no luck. I think it's good more people address this issue to the author.

**Comment by monkoose** [comment]
The problem is that maybe it is not really serve-d issue, but could be partly or fully a coc problem, who knows. Have you addressed this issue to coc devs?

**Comment by vushu** [comment]
Please do, I just havent gotten around doing so.

**Comment by vushu** [comment]
closing this because of fix: https://github.com/Pure-D/serve-d/commit/2bd513a012901a47560e0f69163841aefc61a752
