### ISSUE TITLE
coc-dlang downloads multiple tar files for latest release

### ISSUE THREAD

**Issue by snprajwal** [vushu/coc-dlang#4]
Upon installing coc-dlang, if the `serve-d` binary is not found, the user is made to choose if the latest stable release is downloaded and used. Upon selecting this option, instead of downloading a single tar file, all coc-dlang releases are downloaded, leading to the `tar -xf` command failing after the downloads. I'm unsure why this happens, but I have reproduced it multiple times.

Steps for reproduction:
- Delete all files in `.config/coc/extensions/coc-dlang-data/`
- Open a D file in nvim, CoC will prompt to download and install serve-d
- Choose option 1

System info:
- OS: Arch Linux (6.4.4-arch1-1)
- Nvim: v0.9.1
- Node: v20.4.0
- coc.nvim: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
- coc-dlang: v1.1.6

**Comment by vushu** [comment]
option 1 hasn't been working since there has been alot of changes in serve-d which resulted in coc.nvim not working with it, I would recommend using option 2 or 3.

**Comment by snprajwal** [comment]
Option 2 is working! But I still see a problem with option 1 that's not related to serve-d: multiple tars are downloaded, which should not be happening. I'll try to fix this.

Could you share a little more details about the changes in serve-d that have made it incompatible with coc.nvim? I would like to try fixing this if possible :)

**Comment by vushu** [comment]
indeed that is a bug,

if I recall correctly the stable was working but it depended on you machine the fix was just to bump the openssl version so it wasn't that big
https://github.com/Pure-D/serve-d/pull/227
. The stable is 2 years old I know there has been change in handling messages where serve-d is now using mir-ion a serialization framework.

**Comment by snprajwal** [comment]
I had the issue with libssl on both pre-release and stable versions of serve-d. It currently works with the nightly build from 2 weeks ago 🙌
