### ISSUE TITLE
dub package for dmd not loading

### ISSUE THREAD

**Issue by snprajwal** [vushu/coc-dlang#7]
coc-dlang does not crash anymore, but also shows the following error upon opening a .d file in dmd:
```
Could not initialize dub for /home/prajwalsn/dev/dlang/dmd. Falling back to limited functionality!
Dub package failed to load or no configurations are available, cannot list import paths needed for build and auto-complete.
```
Could you please help with making this work?

**Comment by vushu** [comment]
I think that has something to do with the setup of dmd project, try to ask the author of serve-d for guidens.
